# Generated by Django 5.1.5 on 2025-09-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
